knpu_oauth2_client:
    clients:
        discord:
            type: discord
            client_id: '%env(OAUTH_DISCORD_CLIENT_ID)%'
            client_secret: '%env(OAUTH_DISCORD_CLIENT_SECRET)%'
            redirect_route: security_oauth_discord_connect_redirect
            redirect_params: {}