security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\Authenticators\OAuth\DiscordOAuthAuthenticator
            json_login:
                check_path: security_login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            logout:
                path: security_logout
                target: index
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
            jwt: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/api/v1/news, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_KINGDOM_MEMBER: [ROLE_USER]
        ROLE_ALLIANCE_OFFICER: [ROLE_KINGDOM_MEMBER]
        ROLE_ALLIANCE_LEADER: [ROLE_ALLIANCE_OFFICER]
        ROLE_KINGDOM_COUNCIL: [ROLE_ALLIANCE_LEADER]